name: esptouch_example
description: Demonstrates how to use the esptouch plugin.
publish_to: "none"
version: 0.1.5

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=3.44.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  esptouch_flutter:
    path: ../

flutter:
  config:
    enable-swift-package-manager: true
  uses-material-design: true
